### ISSUE TITLE
domain models

### ISSUE THREAD

**Issue by ahdinosaur** [enspiral-dev-academy/grads#1]
/cc @locksmithdon @donlewi 

instead of directly editing the [domain model wiki page](https://github.com/enspiral-dev-academy/grads/wiki/domain-model), i'd like to start a conversation about the domain models, based on learnings from Holodex and Value Flows.

the core concepts are:
- Agent: something that can act with agency, i.e. a person, group, or bot.
- Account: credentials used for authentication (eventually each agent could have many)
- Profile: an "avatar page" describing an agent
- Relationship: a connection between agents.

---

here's another draft based on Don's initial draft which incorporates [valueflows/agent](https://github.com/valueflows/agent). a major learning of Holodex (from a big mistake) is that relationships are the best way to describe role information (instead of agent types or separate role objects), so i've updated the domain models to reflect this. 

Agent
- hasOne Account
- hasOne AgentType
- hasOne Profile
- hasMany Relationships
- boolean isVisible

Account (credentials)
- email
- username
- password

Profile
- string name
- string note
- string image
- hasMany Highlights
- hasMany Links
- hasMany Tags
- hasMany Contacts

Highlight (bullets of accomplishments, projects, etc)
- belongsTo Profile
- string note

Link (github, projects, etc)
- belongsTo Profile
- string url

Tag (languages, platforms, libraries, etc)
- belongsTo Profile
- string value

Contact (email addresses, phone numbers, etc)
- belongsToProfile
- string value

Relationship
- Agent subject
- RelationshipType relationship
- Agent object
- Agent context

RelationshipType (isMemberOf, isAdminOf, etc)
- string name
- string note

---

thoughts?

**Comment by locksmithdon** [comment]
I really like this. It feels a lot more flexible and elegant. 

Questions:
* Does `note`, `Highlights`, `Links`, and `Tags` make sense for Holodex (Enspiralites)?
* Aren't tags really just groups with an `isMemberOf` relationship type?
* How do we associate rights to roles? Will this happen through `RelationshipType` or will there be a `Right` model and a `hasMany Rights` on the `RelationshipType`?
* I don't feel like I'm clear on the differences between `subject`, `object`, and `context` on the the `Relationship` model. I vaguely remember the terms having specific meanings wrt domain modelling, but my memory fails me. help.

**Comment by ahdinosaur** [comment]
@locksmithdon eep, wanted to use the original markdown from your comment but then accidentally updated your comment instead of posting a new one. i don't get email notifications so i may have lost a couple sentences. :unamused: 

---

> Does `note`, `Highlights`, `Links`, and `Tags` make sense for Holodex (Enspiralites)?

i see all of these as a form of `note`, coming from the inspiration of [the `skos` vocabulary](http://www.w3.org/TR/skos-reference/#notes) where [a note can refer to anything](http://www.w3.org/TR/skos-reference/#L1917). but for now we can try something less general until we get a better idea of how it works.

> Aren't tags really just groups with an `isMemberOf` relationship type?

yeah, that's definitely one way to model them. i'm not sure if it's better to have less concepts (using the existing group with membership relationship concepts) or another more focused concept (a tag is a faceted classification system, more inspiration is [`skos` semantic relations](http://www.w3.org/TR/skos-reference/#semantic-relations)).

> How do we associate rights to roles? Will this happen through `RelationshipType` or will there be a `Right` model and a `hasMany Rights` on the `RelationshipType`?

good question. i made [an old draft vocab](https://github.com/holodex/holodex/issues/70#issuecomment-120225030) where AgentTypes could act as queries on collections of Agents and RelationshipTypes could specify qualifications via a `sourceAgentType`, `targetAgentType`, and `contextAgentType`, but have yet to try any of that in practice.

> I don't feel like I'm clear on the differences between `subject`, `object`, and `context` on the the `Relationship` model. I vaguely remember the terms having specific meanings wrt domain modelling, but my memory fails me. help.

in more usual graph terminology, `subject` is `source` and `object` is `target`. `context` is a special but very necessary concept for determining "where" the relationship exists. for example, i currently [steward](https://github.com/loomio/loomio-org/blob/master/stewarding.md) Matt S within the "context" of Craftworks (`source` = me, `relationship` = `stewards`, `target` = Matt S, `context` = Craftworks). i'd actually be keen to use `source` and `target` to be less confusing.

> I can't think of any reason why we shouldn't update the wiki page to reflect this. There is always history if we need to refer back to it for some reason. But I'm grateful for the discussion here.

keen, just wanted a way to discuss these changes.

**Comment by don-smith** [comment]
Nice topic ... but likely less relevant given the direction this repo is headed.
